### ISSUE TITLE
Upgrade: help needed

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-marketplace#105]
I have successfully added my custom operator to the OperatorHub:

1. oc new-project eclipse-che
2. oc apply -f $operatorsource.yaml:

```
apiVersion: marketplace.redhat.com/v1alpha1
kind: OperatorSource
metadata:
  name: che-operator
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: eivantsov
  displayName: "Community Operators"
  publisher: "Red Hat"
```

3. oc apply -f operatorgroup.yaml:

```
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: che-operator
  namespace: eclipse-che
spec:
  targetNamespaces:
  - eclipse-che
```

I can see my operator in the Hub, I can install it, and it works as expected.

Now I want to test upgrade procedure. My subscription has automatic approval strategy. So, I simply pushed a new app to quay.io. I can see a new tag with 0.0.2 version in quay.

Should I expect my operator to automatically upgrade or do I need to do smth else to make it happen?

```
apiVersion: marketplace.redhat.com/v1alpha1
kind: OperatorSource
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"marketplace.redhat.com/v1alpha1","kind":"OperatorSource","metadata":{"annotations":{},"name":"che-operator","namespace":"openshift-marketplace"},"spec":{"displayName":"Community Operators","endpoint":"https://quay.io/cnr","publisher":"Red Hat","registryNamespace":"eivantsov","type":"appregistry"}}
  creationTimestamp: 2019-02-12T13:10:10Z
  finalizers:
  - finalizer.operatorsources.marketplace.redhat.com
  generation: 1
  name: che-operator
  namespace: openshift-marketplace
  resourceVersion: "4449662"
  selfLink: /apis/marketplace.redhat.com/v1alpha1/namespaces/openshift-marketplace/operatorsources/che-operator
  uid: 86a1e748-2ec7-11e9-ac57-0a0047439e26
spec:
  displayName: Community Operators
  endpoint: https://quay.io/cnr
  publisher: Red Hat
  registryNamespace: eivantsov
  type: appregistry
status:
  currentPhase:
    lastTransitionTime: 2019-02-12T13:10:12Z
    lastUpdateTime: 2019-02-12T13:10:12Z
    phase:
      message: did not find replaces CSV[cheoperator.v0.0.1], channel[alpha] package[che]
      name: Failed
```

Status above suggests that there's no csv cheoperator.v0.0.1. IN what namesapce does it look for it?

I do have csv in the namespaces where the operator is installed:
```
NAME                 AGE
cheoperator.v0.0.1   51m
```

**Comment by aravindhp** [comment]
Did you add a new CSV that replaces the old one as shown in this [example](https://github.com/operator-framework/community-operators/blob/master/community-operators/etcd/etcdoperator.v0.9.2.clusterserviceversion.yaml#L47)?

**Comment by eivantsov** [comment]
@aravindhp  yes, I added it. Here's my 0.0.2 yaml that I used to push to quay.io/eivantsov/cheoperator:0.0.2 https://gist.github.com/eivantsov/19d4b66fdec3141bf8e36beba70a3088

I am stuck with testing how upgrades work - looks like the last piece in my integration puzzle.

**Comment by aravindhp** [comment]
You need to have your 0.0.1 CSV also in the `clusterServiceVersions` section.

**Comment by eivantsov** [comment]
@aravindhp so, every subsequent yaml that I will package as a quay.io app tag should have all preceding clusterserviceversions? Did I get it right?

**Comment by aravindhp** [comment]
That is correct

**Comment by eivantsov** [comment]
@aravindhp thank you. Trying it now.. Is it just enough to push a new tag to quay.io and marketplace operator will re-index somehow? 'Cause I have pushed a new tag and nothing seem to be happening. What I previously did is deleting operatorsource and recreating it to make sure 0.0.2 tag gets listed.

**Comment by aravindhp** [comment]
Marketplace will pick up the updates once an hour. If you want it immediately then deleting the operatorsource will do the trick. You should also be able to force an update by dropping the status block but there is a bug there which will be fixed by #103

**Comment by eivantsov** [comment]
@aravindhp yes, recreating operatorsource did the trick. I can see that a new tag has been added when I click on Operator in OperatorHub:

![image](https://user-images.githubusercontent.com/5337267/52646743-fc80c300-2eeb-11e9-9d9e-5fc684689610.png)

I can see configmap and catalogsource created and no errors on operator-marketplace pod. However, my subscription stays 0.0.1

![image](https://user-images.githubusercontent.com/5337267/52646816-26d28080-2eec-11e9-9036-116e5466fa58.png)

Is there anything else i can take a look at to fix it?

**Comment by aravindhp** [comment]
OK, we will have to reproduce this locally to figure out what is going. In little bit of a time crunch now, so will only get to this next week.

**Comment by eivantsov** [comment]
@aravindhp thanks. If you think i can check some objects and their statuses to figure out what's wrong, do share any ideas.

**Comment by aravindhp** [comment]
@eivantsov I am assuming this has been resolved. Please open a new issue if you are still having trouble.

**Comment by eivantsov** [comment]
Yes, I he issue is resolved. Thanks
