### ISSUE TITLE
CatalogSourceConfig `kubectl` Output Difficult to Read

### ISSUE THREAD

**Issue by alecmerdler** [operator-framework/operator-marketplace#116]
### Description

Having [seven items in the `additionalPrinterColumns`](https://github.com/operator-framework/operator-marketplace/blob/master/deploy/crds/catalogsourceconfig.crd.yaml#L19) for the `CatalogSourceConfig` CRD makes the rendered output from `kubectl get` difficult to read on even wide terminals (see screenshots). Consider reducing the number of fields being displayed. Changing `spec.packages` from being a comma-separated string to a proper array would likely help as well.

### Screenshots

**Viewing `CatalogSourceConfigs`:**
![screenshot_20190225_135813](https://user-images.githubusercontent.com/11700385/53361386-a6f1e080-3905-11e9-9ae5-c1ad6f93312c.png)

**Viewing `Pods`:**

![screenshot_20190225_135919](https://user-images.githubusercontent.com/11700385/53361409-ae18ee80-3905-11e9-996c-e1707ca0cc10.png)

**Comment by aravindhp** [comment]
@alecmerdler added a Jira story to track and fix this
