### ISSUE TITLE
Can't install a custom operator

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-marketplace#122]
It was working on a cluster installed from 0.12.0 installer tag, after update to 0.13.1 I cannot install an operator from a custom OperatorSource:

```
apiVersion: marketplace.redhat.com/v1alpha1
kind: OperatorSource
metadata:
  name: codeready-operator
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: eivantsov
  displayName: "Custom Operators"
  publisher: "Red Hat"
```

After I create a custom operatorsource, I can see my operator in the Operator Marketplace. I then install it. A subscription is created. However, this subscription is bound to a non-existing catalogSource `installed-custom-openshift-operators`

What is the right way to install an Operator that comes from a custom OperatorSource?

I can see this in catalog operator pod in olm namespace:

```
E0301 11:32:31.082993       1 queueinformer_operator.go:155] Sync "openshift-operators" failed: {codeready alpha crwoperator.v1.0.1 {installed-custom-openshift-operators openshift-operators}} not found: CatalogSource {installed-custom-openshift-operators openshift-operators} not found
time="2019-03-01T11:32:31Z" level=info msg="retrying openshift-operators"
```

I can see that my CatalogSourceConfig has problems:

```
eugene@ivantsoft ~/go/src/github.com/operator-framework/operator-marketplace/scripts (master) $ oc get catalogsourceconfig/installed-custom-openshift-operators -n=openshift-marketplace -o=yaml
apiVersion: marketplace.redhat.com/v1alpha1
kind: CatalogSourceConfig
metadata:
  creationTimestamp: 2019-03-01T10:38:33Z
  finalizers:
  - finalizer.catalogsourceconfigs.marketplace.redhat.com
  generation: 1
  name: installed-custom-openshift-operators
  namespace: openshift-marketplace
  resourceVersion: "47494"
  selfLink: /apis/marketplace.redhat.com/v1alpha1/namespaces/openshift-marketplace/catalogsourceconfigs/installed-custom-openshift-operators
  uid: 29b74be8-3c0e-11e9-be55-024be96b7e64
spec:
  csDisplayName: Custom Operators
  csPublisher: Custom
  packages: codeready
  targetNamespace: openshift-operators
status:
  currentPhase:
    lastTransitionTime: 2019-03-01T10:38:33Z
    lastUpdateTime: 2019-03-01T10:38:33Z
    phase:
      message: Still resolving package(s) - codeready. Please make sure these are
        valid packages.
      name: Configuring
```

How can I find out what causes problems with resolving a package?

**Comment by SamiSousa** [comment]
@eivantsov Sorry for the delay in getting back to you. If you're installing your operator via the UI, then a CatalogSourceConfig and Subscription should be created, as you have seen. It seems that either the package `codeready` doesn't match a valid package or something is wrong with the marketplace operator pod.
In the first case, you should check your operator's `package.yaml` file and make sure the packageName matches the one in the CSC above. Make sure the quay repo has a matching name to this as well.
In the second case, look at the logs for the marketplace-operator pod in the `openshift-marketplace` namespace.
If you could recreate this issue, let us know; we'd be happy to help hone in on the issue.

**Comment by eivantsov** [comment]
@SamiSousa thanks. It turned out after another update package name and quay repo name have to be identical, whilst it was not required before.
