### ISSUE TITLE
error: unable to recognize "operator-marketplace/deploy/upstream/07_upstream_operatorsource.cr.yaml": no matches for kind "OperatorSource" in version "operators.coreos.com/v1"

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-marketplace#243]
The error `error: unable to recognize "operator-marketplace/deploy/upstream/07_upstream_operatorsource.cr.yaml": no matches for kind "OperatorSource" in version "operators.coreos.com/v1"` is faced when we run `kubectl apply -f operator-marketplace/deploy/upstream/` as described here: https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md#3-install-the-operator-marketplace

**Comment by dmesser** [comment]
@camilamacedo86 This is an issue with `kubectl` trying to apply the the CR too fast. If you just repeat the `apply -f` command it will work. In this case (local testing) it's not too much of an issue since just the community catalog will not be loaded.

**Comment by camilamacedo86** [comment]
Hi @dmesser, 

I thought that as some issue the group definitions. Thank you for your explanation. I checked that besides the error it was applied.
