### ISSUE TITLE
Alerting rules incomplete 

### ISSUE THREAD

**Issue by lilic** [operator-framework/operator-marketplace#264]
Hello from the openshift monitoring team, I noticed that you could improve your alerts a bit. 👋 

Couple of things to change:
- Name should be PascalCase, see [alerts](https://github.com/openshift/cluster-monitoring-operator/blob/7977e1dc22556218bfd7276cb0ed9b7e10590af8/assets/prometheus-k8s/rules.yaml) for examples. so `community-operators-alert` -> `CommunityOperatorsAlert`
- Naming of the alerts don't fall into best practices, I would suggest instead of `CommunityOperatorsAlert` -> `CommunityOperatorsRegistryErrors`
- The alert expression itself you are not doing an actual error rate, you should compare the errors with total success.
- Another thing missing is description, so to each alert you should add:
```
 annotations:
        description: 
        summary: Fill in the summary.
```
- Also would suggest adding:
```
      for: 15m
      labels:
        severity: warning
```
Currently we are seeing this in Alertmanager, this does not customers what to do in the case this alert fires:
<img width="973" alt="Screenshot 2019-10-30 at 13 36 14" src="https://user-images.githubusercontent.com/6232346/67944158-1da15500-fbdc-11e9-958f-aa1c2348fbfe.png">
We want to end up with something like this:
<img width="1434" alt="Screenshot 2019-10-31 at 12 57 34" src="https://user-images.githubusercontent.com/6232346/67944958-12e7bf80-fbde-11e9-9438-b7e9fd602977.png">

See [alerting rules docs](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/) for more information. Also example of error rate alert [here](https://github.com/openshift/cluster-monitoring-operator/blob/7977e1dc22556218bfd7276cb0ed9b7e10590af8/assets/prometheus-k8s/rules.yaml#L372-L380).

Let me know if you have any questions. :)

**Comment by LiliC** [comment]
cc @awgreene ^

**Comment by awgreene** [comment]
@LiliC Thanks for reporting this.

Please see the WIP PR: https://github.com/operator-framework/operator-marketplace/pull/259
