### ISSUE TITLE
Question: 2 operators having different install plan deployed within same namespace

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-marketplace#281]
## Question

How to manage such use case as currently it is only possible to install an operatorGroup / namespace ?

We would like to install within the namespace `marketplace` 2 operators. The namespace `marketplace` contains the  `OperatorSource` and  generated `catalogSource` of the `Community Operators`. This namespace contains also an operatorGroup which do not include any `targetNamespaces`

Question: Is it possible to install 2 operators within the namespace marketplace where : 
- one has an `InstallPlan` defined with the CSV equal to [`AllNamespace`](https://github.com/operator-framework/community-operators/blob/master/community-operators/openshift-pipelines-operator/0.10.4/openshift-pipelines-operator.v0.10.4.clusterserviceversion.yaml#L381-L382)
- Another where the `InstallPlan` is `Namespace` [scoped](https://github.com/operator-framework/community-operators/blob/master/community-operators/prometheus/0.32.0/prometheusoperator.0.32.0.clusterserviceversion.yaml#L304-L305)

If this is not possible, what is then the alternative solution ?

**Comment by njhale** [comment]
This issue is stale/rotten, but in case you're still wondering: you _can only have one active OperatorGroup per namespace_.

(also, this question belongs in the operator-lifecycle-manager repo)
