### ISSUE TITLE
shared package importing  non existing package k8sutil from operator-sdk

### ISSUE THREAD

**Issue by Kaitou786** [operator-framework/operator-marketplace#333]
Hi, recently operator-sdk v1.0.0 was released we're trying to upgrade to that, we are using the master of operator-marketplace which has [shared](https://github.com/operator-framework/operator-marketplace/blob/master/pkg/apis/operators/shared/shared.go#L4) package, tries to import `k8sutil` package from operator-sdk which is now moved to an internal package in this release [see](https://github.com/operator-framework/operator-sdk/tree/master/internal/util/k8sutil). This import causes the following stack trace:
```
 github.com/operator-framework/operator-marketplace/pkg/apis/operators/v1 imports
        github.com/operator-framework/operator-marketplace/pkg/apis/operators/shared imports
        github.com/operator-framework/operator-sdk/pkg/k8sutil: module github.com/operator-framework/operator-sdk@latest found (v1.0.0), but does not contain package github.com/operator-framework/operator-sdk/pkg/k8sutil
```

**Comment by balpert89** [comment]
I am hitting this too with our operators.

**Comment by Kaitou786** [comment]
@balpert89 this got resolved for me please see: https://github.com/operator-framework/operator-sdk/issues/3792
