### ISSUE TITLE
Missing operators in packagemanifests

### ISSUE THREAD

**Issue by JoaoBraveCoding** [operator-framework/operator-marketplace#341]
So I'm running OKD v4.5 and I wanted to install the `cluster-logging` operator in my cluster but I ran into a few problems. I followed the instructions in the [OKD Docs](https://docs.okd.io/latest/logging/cluster-logging-deploying.html#cluster-logging-deploy-cli_cluster-logging-deploying) where at some point I have to create a `Subscription` resource pointing to the `redhat-operators` `CatalogSource`. My first problem was that the only `CatalogSource` I had in my cluster was the `community-operators`, is this normal?  Because from [this issue](https://github.com/operator-framework/operator-marketplace/issues/247#issuecomment-531032981) it seems that it's not.

I solved my first problem by just manually creating the `CatalogSource` CR but unfortunately then when I listed the available package manifests with ` oc get packagemanifest -n openshift-marketplace` the `cluster-logging` operator doesn't show up. I also noticed that the number of operators that appeared by adding `redhat-operators` was very low (only 11), where other users have many more, as seen in [this comment](https://github.com/operator-framework/operator-lifecycle-manager/issues/1530#issuecomment-631023848).

**Comment by JoaoBraveCoding** [comment]
Closing given https://github.com/openshift/okd/issues/295

**Comment by apakhbari** [comment]
Hi there,
For future references:  had same issue, In Cuuster's OperatorHub, changed disabled default sources to false.
