### ISSUE TITLE
Marketplace Operator in OKD

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-marketplace#95]
README says 

> The Marketplace Operator is deployed by default with OKD and no further steps are required.

However, with OKD 3.11 I see only two operators:

```
eugene@ivantsoft ~/Downloads/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit $ oc get pods --all-namespaces
NAMESPACE                       NAME                                                      READY     STATUS      RESTARTS   AGE
default                         docker-registry-1-8992s                                   1/1       Running     0          8m
default                         persistent-volume-setup-k2jpx                             0/1       Completed   0          8m
default                         router-1-8n27x                                            1/1       Running     0          8m
kube-dns                        kube-dns-xhkfk                                            1/1       Running     0          10m
kube-proxy                      kube-proxy-8chgs                                          1/1       Running     0          10m
kube-system                     kube-controller-manager-localhost                         1/1       Running     0          10m
kube-system                     kube-scheduler-localhost                                  1/1       Running     0          9m
kube-system                     master-api-localhost                                      1/1       Running     0          9m
kube-system                     master-etcd-localhost                                     1/1       Running     0          9m
openshift-apiserver             openshift-apiserver-jp9vk                                 1/1       Running     0          10m
openshift-controller-manager    openshift-controller-manager-4zglb                        1/1       Running     0          8m
openshift-core-operators        openshift-service-cert-signer-operator-6d477f986b-8mc6l   1/1       Running     0          10m
openshift-core-operators        openshift-web-console-operator-664b974ff5-lf6sr           1/1       Running     0          8m
openshift-service-cert-signer   apiservice-cabundle-injector-8ffbbb6dc-6wfrb              1/1       Running     0          9m
openshift-service-cert-signer   service-serving-cert-signer-668c45d5f-m2fqv               1/1       Running     0          9m
openshift-web-console           webconsole-595b6b5d9-mgprj                                1/1       Running     0          7m
```
There's no OLM in OKD by default as well, so I wonder if existing instruction are accurate.
Thanks

**Comment by SamiSousa** [comment]
@eivantsov The Marketplace Operator is deployed be default in OKD 4.0 clusters by default. We will update the readme to more accurately reflect this. Thank you for bringing this to our attention!

**Comment by eivantsov** [comment]
@SamiSousa thanks. I have deployed OLM and Operator resources. 

I think the same concerns?

> The package-server, managed by OLM, will then respond to the creation of these CRs and allow the external operators to be visible in the marketplace UI.

Btw, broken link there.

I have deployed OLM and launched an admin console as per https://github.com/operator-framework/operator-lifecycle-manager#user-interface:

![image](https://user-images.githubusercontent.com/5337267/51394010-33d79c00-1b07-11e9-87f1-5bcd05475850.png)

Now, where should I look for operators from the marketplace?

Thanks for your help. I am investigating ways to intergate Eclipse Che Operator into OLM/Marketplace.

**Comment by SamiSousa** [comment]
To deploy the Marketplace Operator on a 3.11 cluster, follow the steps under `Deploying the Marketplace Operator with Kubernetes`. Once the operator is running, you should create an OperatorSource CR (you can use the example found [here](https://github.com/operator-framework/operator-marketplace/blob/master/deploy/examples/operatorsource.cr.yaml)) setting the `registryNamespace` field under `spec` with a quay.io registry name. In 4.0 we ship with 3 default OperatorSource CRs pointing to `redhat-operators`, `certified-operators`, and `community-operators`, so you could use one of these.
I'm not completely sure it will work since we've been developing Marketplace on OKD 4.0 using the installer, but if you are using the latest version of OLM and the latest version of the OpenShift console, you may have some luck. :)

**Comment by eivantsov** [comment]
Thanks. I am lucky and it worked :)

![image](https://user-images.githubusercontent.com/5337267/51395230-528b6200-1b0a-11e9-96b8-fc7ff6217969.png)

However, the Operator Marketplace status is Failed:

![image](https://user-images.githubusercontent.com/5337267/51395252-620aab00-1b0a-11e9-9dd2-c3493acd5489.png)

I do not see any errors in this operator's pod logs

**Comment by SamiSousa** [comment]
The UI seems to have reverted to an older style, which is odd.
If you have access to the cluster via command line, I recommend running `oc get catalogsourceconfigs -n openshift-marketplace` and see what prints out.

**Comment by eivantsov** [comment]
```
eugene@ivantsoft ~/go/src/github.com/operator-framework/operator-marketplace (master) $ oc get catalogsourceconfigs -n openshift-marketplace
NAME                                      AGE
example                                   16m
marketplace-enabled-operators-undefined   5m
```

**Comment by eivantsov** [comment]
And further question:

I tried to install Prometheus operator, chose update channel and global group.  Upon clicking create I was taken to the operator list screen.

The operator is displayed as installed here:

![image](https://user-images.githubusercontent.com/5337267/51397683-ba907700-1b0f-11e9-9168-059802f00143.png)

But not here:

![image](https://user-images.githubusercontent.com/5337267/51397707-c4b27580-1b0f-11e9-9170-6316cf1774fc.png)

In general, is it a good idea to try it with 3.11?? Or in other words, what would be the right way to:

1. Deploy a local OpenShift instance
2. Enable Operator Marketplace
3. Experiment with integrating own Operator in it

**Comment by SamiSousa** [comment]
If you build and run the openshift-installer from the master branch, you will get a 4.0 cluster that has Marketplace by default. It has some rough edges, but this is the best way to try experimenting with Marketplace right now.

**Comment by SamiSousa** [comment]
Also, to see the installed operators you should go to the `openshift-operators` project since the installed operators will be namespaced.

**Comment by SamiSousa** [comment]
@eivantsov I made a PR addressing some of your comments, specifically about the README not specifying that Marketplace is deployed by default only on OKD 4.0, and fixing the broken link. Let me know your thoughts.

**Comment by eivantsov** [comment]
The last error was against 3.9 not 3.11.
