### ISSUE TITLE
Cannot create a subscription from a marketplace operator

### ISSUE THREAD

**Issue by eivantsov** [operator-framework/operator-marketplace#97]
Here's a short video:

https://www.youtube.com/watch?v=khnlM84cIjQ

Basically nothing happens. I am using 3.11 OKD + admin console started as a Docker container.

**Comment by aravindhp** [comment]
Unfortunately we don't support Marketplace on 3.11. Please try with OKD 4.0 beta 2 when it is released.

**Comment by eivantsov** [comment]
@aravindhp thanks

**Comment by eivantsov** [comment]
@aravindhp only beta 2? Does it make sense to install now using https://github.com/openshift/installer?

**Comment by aravindhp** [comment]
It should work if you build the installer from master and deploy to a cluster.
